services:
    - docker

before_install:
    - docker --version

install:
    - git clone https://github.com/docker-library/official-images.git official-images

# Assist with ci test debugging:
#   - DEBUG=1
before_script:
    - image="kylemanna/syncthing-relay"
    - docker build -t "$image" .
    - docker inspect "$image"

script:
    - official-images/test/run.sh -t utc -t cve-2014--shellshock -t no-hard-coded-passwords "$image"

after_script:
    - docker images
